# Generated by Django 6.0 on 2025-12-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_datospersonales_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_garage/'),
        ),
    ]
